modLoader="neoforge"
loaderVersion="[20,)"
license="MIT"

[[mods]]
modId="setspawnmod"
version="1.0"
displayName="Set Spawn Mod"
description='''Adds /setspawn and /spawn commands'''
authors="YourName"
